kind: Service
apiVersion: v1
metadata:
  name: api-service
  labels:
    app.kubernetes.io/name: node-db-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: node-db-api
    app.kubernetes.io/part-of: node-db-api
    app.kubernetes.io/managed-by: helm3
spec:
  selector:
    app.kubernetes.io/name: node-db-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
